#!/usr/bin/env bash
sleep_time=2
jobid=`(
  echo "#!/usr/bin/env bash"
  echo "#PBS -N Regression_dealII"
  echo "#PBS -l nodes=1:VAR_PBS_PROPERTIES"
  echo "#PBS -u pbs"
  echo "d=\\\$HOME/\\\$PBS_JOBID"
  echo "function stagein()"
  echo "{"
  echo "  scp \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/input_ref.tar.bz2 ."
  echo "  scp \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/dealII ."
  echo "}"
  echo "function stageout()"
  echo "{"
  echo "  scp grid-0.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-1.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-2.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-3.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-4.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-5.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-6.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-7.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-8.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-0.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-1.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-2.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-3.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-4.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-5.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-6.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-7.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-8.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-10.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-11.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-12.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-13.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-14.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-15.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-16.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-17.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-18.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-19.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-20.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-21.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-22.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-23.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grid-9.eps \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp log \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-10.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-11.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-12.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-13.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-14.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-15.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-16.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-17.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-18.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-19.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-20.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-21.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-22.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-23.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp solution-9.gmv \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "}"
  echo "function run()"
  echo "{"
  echo "  tar xf input_ref.tar.bz2"
  echo "  ./do_runme_ref.sh"
  echo "}"
  echo "olddir=\\\$PWD"
  echo "mkdir -p \\\$d && cd \\\$d"
  echo "echo host: \\\`uname -n\\\`"
  echo "stagein"
  echo "run"
  echo "stageout"
  echo "cd \\\$olddir"
  echo "rm -r \\\$d"
) | qsub`
status=`qstat | grep $jobid`
while [ -n "$status" ]; do
  sleep $sleep_time
  status=`qstat | grep $jobid`
done
