#!/usr/bin/env bash
sleep_time=2
jobid=`(
  echo "#!/usr/bin/env bash"
  echo "#PBS -N Regression_perlbench"
  echo "#PBS -l nodes=1:VAR_PBS_PROPERTIES"
  echo "#PBS -u pbs"
  echo "d=\\\$HOME/\\\$PBS_JOBID"
  echo "function stagein()"
  echo "{"
  echo "  scp \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/input_test.tar.bz2 ."
  echo "  scp \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/perlbench ."
  echo "}"
  echo "function stageout()"
  echo "{"
  echo "  scp append.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp args.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp arith.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp array.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp attrs.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp auto.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp base_cond.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp base_pat.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp base_term.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp bless.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp bop.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp bproto.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp chars.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp chop.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp cmdopt.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp cmp.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp comp_term.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp concat.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp context.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp decl.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp defins.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp delete.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp die.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp do.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp each.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp eval.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp exists_sub.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp exp.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp fh.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp grep.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp gv.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp hashwarn.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp if.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp inc.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp index.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp int.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp join.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp length.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp lex.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp list.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp loopctl.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp lop.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp makerand.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp method.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp my.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp nothr5005.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp oct.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp op_cond.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp op_pat.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp ord.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp override.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp pack.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp package.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp pos.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp push.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp quotemeta.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp range.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp recurse.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp redef.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp ref.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp regexp.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp regexp_noamp.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp regmesg.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp repeat.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp reverse.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp rs.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp sleep.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp sort.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp splice.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp study.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp sub_lval.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp subst.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp subst_amp.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp subst_wamp.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp tr.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp undef.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp unshift.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp vec.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "  scp wantarray.out \\\$PBS_O_HOST:\\\$PBS_O_WORKDIR/"
  echo "}"
  echo "function run()"
  echo "{"
  echo "  tar xf input_test.tar.bz2"
  echo "  ./do_runme_test.sh"
  echo "}"
  echo "olddir=\\\$PWD"
  echo "mkdir -p \\\$d && cd \\\$d"
  echo "echo host: \\\`uname -n\\\`"
  echo "stagein"
  echo "run"
  echo "stageout"
  echo "cd \\\$olddir"
  echo "rm -r \\\$d"
) | qsub`
status=`qstat | grep $jobid`
while [ -n "$status" ]; do
  sleep $sleep_time
  status=`qstat | grep $jobid`
done
